[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "hello"
version = "0.1.0"
description = "Tiny demo project for GitHub Actions"
requires-python = ">=3.10"
