version: "3.9"
services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.15.1
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root /mlruns
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
      - ./mlflow.db:/mlflow.db

  api:
    build: .
    environment:
      USE_MLFLOW: "true"
      MLFLOW_TRACKING_URI: "http://mlflow:5000"
      MODEL_NAME: "iris-classifier"
      MODEL_STAGE: "Staging"
    ports:
      - "8000:8000"
    depends_on:
      - mlflow
    volumes:
      - ./models:/app/models
